version : '2'

services:
  
  postgres:
      container_name: postgres
      image: 'bitnami/postgresql:latest'
      environment:
        - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
        - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
        - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
      ports:
        - ${PG_PORT}:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - ${PG_ADMIN_PORT}:80
    depends_on:
      - postgres
    networks:
      - default

  user_tags:
    build:
      context: ./UserTag    
    restart: always
    ports:
      - ${SERVER_PORT}:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - secret=${secret}
    networks:
      - default      

networks:
  default:
