version : '2'

services:
  
  postgres:
      container_name: postgres
      image: 'bitnami/postgresql:latest'
      environment:
        - POSTGRESQL_USERNAME=mihail
        - POSTGRESQL_PASSWORD=password123
        - POSTGRESQL_DATABASE=test_db
      ports:
        - 5432:5432
  pgadmin:
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    depends_on:
      - postgres

  user_tags:
    build:
      context: ./UserTags    
    restart: always
    ports:
      - 3001:3000
    environment:
      - DATABASE_URL=postgres://mihail:password123@postgres:5432/test_db
      - secret=bigsecret
